### PR TITLE
Update database.md

### PR DESCRIPTION
**Pull request by ghost**
Arch Linux | ARM

### CODE REVIEW

**Comment by ghost** [comment]
Operating system ... of course ;)

**Comment by shoeper** [comment]
The architecture is not relevant, is it?

**Comment by ghost** [comment]
Well, If you're using it like for the Raspberry Pi this can be helpful.

Edit: 
I'm using Arch for the Pi as a server. You could also use the AUR-Seafile Server but I think it's better to handle this way. It's actually nearly the same way like on Debian.

**Comment by shoeper** [comment]
I'm not talking about this shouldn't be merged, but whether it is arch on a pi or x86 seems to be completely irrelevant.

**Comment by ghost** [comment]
Hm, I don't understand you.

I mean ARM isn't x86. Sry but I don't get it :)

Or do you mean that I specify it as "... | ARM"?
If it's so the way is different compared to Arch x64. And the easiest way (at the moment) is to use ARM instead of AArch 64 on a Raspberry Pi.

Edit:
We're nearly on the move to try this on a Desktop/x64 Computer. But like I said it's different. I think it's not necessary to use the AUR - libsepol & libselinux on a x64 arch. And I don't wanna use the AUR Repo if it's not really necessary.

**Comment by shoeper** [comment]
> Or do you mean that I specify it as "... | ARM"?

Yes. I don't see anything that looks specific to arm.

**Comment by ghost** [comment]
Like I said it might be different to 64 (AUR). 
And cower isn't installed on 64 I think it's only available through AUR but it's already included on ARM. So we could add this too.

**Comment by shoeper** [comment]
Only commands I see in this PR are

```
root@cloudserver:~# pacman -S mariadb
root@cloudserver:~# mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
root@cloudserver:~# mysql_secure_installation
```

I don't see anything specific to any architecture. Could have missed something, though. I'd keep it as generic as possible.

@DerDanilo can decide how to continue.

**Comment by ghost** [comment]
Yes you are right. But only in this file. The other pull request refers to the arm os. I think it's better to stay that way. In the end it will be clearer for everyone.

As you said, let's wait for Danilo.

**Comment by DerDanilo** [comment]
Sorry for the delay. The end of the year is just super busy. This all sounds reasonable. I believe all is tested?

**Comment by ghost** [comment]
No problem.
It is. Only 64Bit isn't.

**Pull request merged**
