### PR TITLE
Instructions for ARM64 added

### PR DESCRIPTION
**Pull request by bionade24**
Maybe this topic should get a other headline than **Operating Systems**

### CODE REVIEW

**Comment by DerDanilo** [comment]
I would like to include all guides and resources within this manual. So no links to potential dead to be forum posts, blogs or websites. 
Can you please have a look how the installation instructions work for the setup and include the arm guide into them?

You did this already correct for the operating system. Now just go to every other page and drop the part that important for the arm based setup.
Thinks like network, nginx config (not setup) and ssl can be left out I guess. Maybe even more, since it's generic in every system.

No time pressue. If the information makes it into the manual before christmas it's already super fast, considering it's "age".

Thanks!

**Review by DerDanilo — CHANGES_REQUESTED** [review]
Please see the comment in the PR

**Comment by DerDanilo** [comment]
@bionade24 Any progress?

**Comment by bionade24** [comment]
I currently have many tests at school and stress with other projects, so I didn't already have time for this. But I haven't forgot it and will contribute much from around the mid of December on.

**Pull request merged**
